### ISSUE TITLE
Improve GNN architectures

### ISSUE THREAD

**Issue by smsharma** [smsharma/point-cloud-galaxy-diffusion#9]
- [ ] Fix equivariant norm in the EGNN
- [ ] Add attention to both EGNN and GNN
- [ ] Unify EGNN and GNN (make them the same function, or make the functions more similar)
- [ ] Add random graphs
- [ ] Add globals to the EGNN node updates
- [ ] Understand how globals are treated -- treat as scalars?

**Comment by florpi** [comment]
- [ ] Fourier features / Bessel wathever
- [ ] Centering for translation invariance
